base_url = "https://drainpixie.me"
build_search_index = false
generate_feeds = true
compile_sass = false

taxonomies = [
    { name = "tags", feed = true },
]

[markdown]
highlight_code = true
highlight_theme = "gruvbox-light"

[extra]
